### ISSUE TITLE
Pronunciation of Project Name?

### ISSUE THREAD

**Issue by larsenv** [queer/qit#1]
How do you pronounce the project's name? Is it pronounced as you would say "quit"? If so, that makes the project sound like it's not only a thing to ween you off of using git like a program to get you to stop smoking cigarettes, but it also sounds like it's a Qt GUI for git.

I'm not sure I like this name, it reminds me of https://www.reddit.com/r/funny/comments/4ihutx/found_out_ismarts_logo_reads_jews_when_upside_down/

On another note, how does one remember to type in qit instead of git? I'm sure that if you use git in the CLI long enough, you'll always accidentally type in git instead of qit going forward.

**Comment by queer** [comment]
> Is it pronounced as you would say "quit"?

I pronounce it similar to the word "`kit`," personally.

> On another note, how does one remember to type in qit instead of git?

I developed the habit easily-enough, and since it's primarily intended for me, I considered it good enough. I'm open to suggestions :woman_shrugging:

When I named it, the only thought I had was this:

![](https://cdn.mewna.xyz/2021/12/15/iuUEm5GXT0N58.png)

Converting a lowercase "`g`" to a lowercase "`q`" seemed like a simple-enough transformation to make to make it memorable as well as easy to type still.
